// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Activity struct {
	ID        string    `json:"id"`
	TaskID    string    `json:"taskId"`
	ProjectID string    `json:"projectId"`
	User      *User     `json:"user"`
	Action    string    `json:"action"`
	OldValue  *string   `json:"oldValue,omitempty"`
	NewValue  *string   `json:"newValue,omitempty"`
	Metadata  *string   `json:"metadata,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
}

type Comment struct {
	ID        string    `json:"id"`
	TaskID    string    `json:"taskId"`
	User      *User     `json:"user"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type CreateTaskInput struct {
	ProjectID   string     `json:"projectId"`
	ParentID    *string    `json:"parentId,omitempty"`
	Title       string     `json:"title"`
	Summary     *string    `json:"summary,omitempty"`
	StatusID    *string    `json:"statusId,omitempty"`
	AssigneeID  *string    `json:"assigneeId,omitempty"`
	Priority    Priority   `json:"priority"`
	DueDate     *time.Time `json:"dueDate,omitempty"`
	ProgressPct *int       `json:"progressPct,omitempty"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateTaskInput struct {
	Title       *string    `json:"title,omitempty"`
	Summary     *string    `json:"summary,omitempty"`
	StatusID    *string    `json:"statusId,omitempty"`
	AssigneeID  *string    `json:"assigneeId,omitempty"`
	Priority    *Priority  `json:"priority,omitempty"`
	DueDate     *time.Time `json:"dueDate,omitempty"`
	ProgressPct *int       `json:"progressPct,omitempty"`
}

type WorkflowStatusInput struct {
	Name       string `json:"name"`
	Color      string `json:"color"`
	Position   int    `json:"position"`
	IsTerminal bool   `json:"isTerminal"`
}
